"""empty message

Revision ID: 5d3cae42675d
Revises: 7cc8a9a0b0cb
Create Date: 2021-05-02 19:19:32.057630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3cae42675d'
down_revision = '7cc8a9a0b0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
